// Vendor
import 'bootstrap/scss/bootstrap.scss';
// Common
import '../../styles/style.scss';
// Local
import './team.scss';
// Inline
import './inline/inlineTeam';
import './inline/inlineTeam.scss';
