// Vendors
import 'bootstrap.scss';
import 'collapse';
// Common
import 'style.scss';
import '../../scripts/components/sticky';
import '../../scripts/components/social';
// Local
import './requisites.scss';
// Inline
