// Vendors
import 'bootstrap.scss';
import 'collapse';
// Common
import '../../styles/main.scss';
import '../../scripts/components/sticky';
import '../../scripts/components/icons';
import '../../scripts/components/gototop';
import '../../scripts/components/fon';
import '../../scripts/components/logo';
// Local
import './requisites.scss';
