// Vendor
import 'bootstrap/scss/bootstrap.scss';
// Common
import '../../styles/style.scss';
// Local
import './eventsboard.scss';
// Inline
import './inline/inlineEventsboard';
import './inline/inlineEventsboard.scss';
