// Vendor
import 'bootstrap/scss/bootstrap.scss';
// Common
import '../../../styles/style.scss';
// Local
import './coach.scss';
// Inline
import './inline/inlineCoach';
import './inline/inlineCoach.scss';
