// Vendors
import 'bootstrap.scss';
import 'carousel';
import 'collapse';
// Common
import '../../../styles/main.scss';
import '../../../scripts/components/sticky';
import '../../../scripts/components/icons';
import '../../../scripts/components/gototop';
// Local
import './service.scss';
