// Vendor
import 'bootstrap/scss/bootstrap.scss';
// Common
import '../../styles/style.scss';
// Local
import './coaches.scss';
// Inline
import './inline/inlineCoaches';
import './inline/inlineCoaches.scss';
